version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: monthly
      time: '06:00'
    rebase-strategy: 'disabled'
    target-branch: main
    open-pull-requests-limit: 10
    groups:
      production-dependencies:
        dependency-type: 'production'
      development-dependencies:
        dependency-type: 'development'
      nx:
        patterns:
          - '@nx*'
          - '@nrwl*'
          - 'nx*'
        update-types:
          - 'minor'
          - 'patch'
      babel:
        patterns:
          - '@babel*'
      typescript:
        patterns:
          - 'typescript'
          - '@typescript*'
      commitlint:
        patterns:
          - '@commitlint*'
      eslint:
        patterns:
          - 'eslint'
        update-types:
          - 'minor'
          - 'patch'
      stylelint:
        patterns:
          - 'stylelint'
        update-types:
          - 'minor'
          - 'patch'
